name: OpenWrt Image Build (TL-WR840N v6.2 - 4MB Flash)

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: 'OpenWrt Release (MUST be 19.07.x for 4MB flash)'
        required: true
        default: '19.07.10'

env:
  # Preferred profile string you attempted; workflow will detect exact available profile or fallback
  TARGET_PROFILE: tplink_tl-wr840n-v6-us
  # Minimal package list for 4MB builds on 19.07.x (adjust if you need to shrink)
  PACKAGES: "nodogsplash wpad-basic-mbedtls -luci -opkg -ppp -pppoe -ip6tables -odhcpd-ipv6only -kmod-ipv6 -kmod-ppp"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up environment debug info
        run: |
          echo "GITHUB_WORKSPACE=${GITHUB_WORKSPACE}"
          echo "TARGET_PROFILE=${{ env.TARGET_PROFILE }}"
          echo "PACKAGES=${{ env.PACKAGES }}"

      - name: Download ImageBuilder
        run: |
          VERSION="${{ github.event.inputs.openwrt_version }}"
          BUILDER_URL="https://downloads.openwrt.org/releases/${VERSION}/targets/ramips/mt76x8/openwrt-imagebuilder-${VERSION}-ramips-mt76x8.Linux-x86_64.tar.xz"
          echo "Downloading ImageBuilder from: $BUILDER_URL"
          wget -q --show-progress "$BUILDER_URL" -O imagebuilder.tar.xz
          tar -xf imagebuilder.tar.xz
          BUILDER_DIR=$(tar -tf imagebuilder.tar.xz | head -1 | cut -f1 -d"/")
          echo "BUILDER_DIR=$BUILDER_DIR" >> $GITHUB_ENV

      - name: Show available profiles (debug)
        run: |
          cd "${{ env.BUILDER_DIR }}"
          echo "Profiles containing 'wr840' (for debug):"
          make info | grep -i wr840 || true
          echo "Profiles containing 'tl-wr840' (for debug):"
